language: node_js
node_js:
  - node

script:
  - make test

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c "create user travis_ci_test_user WITH PASSWORD 'rrwcscrz2';" -U postgres
  - 'npm run create'

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10

env:
  global:
  - PGPORT=5432

